### ISSUE TITLE
谢谢分享~~~~~

### ISSUE THREAD

**Issue by LeeQiWei** [tancolo/IDouban#1]
谢谢分享~~~~受益匪浅
另外，能把Retrofit + RxJava的也分享一下么，哈哈哈哈

**Comment by tancolo** [comment]
这个已经实现，在dev分支中。
使用git checkout dev切换到dev分支，就可以看到新增以及修改的内容了。

**Comment by LeeQiWei** [comment]
非常感谢咯，哈哈哈

**Comment by tancolo** [comment]
后续有问题，直接在issues中提出，觉得好的话，请推荐给其他需要的人。Thank you!

**Comment by LeeQiWei** [comment]
好哒好哒，先谢谢啦~~~~~~
